/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.24
 * Generated at: 2019-10-04 07:36:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.URL;
import java.nio.file.Paths;
import java.nio.file.Path;

public final class CourseV_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.nio.file.Paths");
    _jspx_imports_classes.add("java.net.URL");
    _jspx_imports_classes.add("java.nio.file.Path");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<title>Education &mdash; Free Website Template, Free HTML5\r\n");
      out.write("\tTemplate by freehtml5.co</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"description\"\r\n");
      out.write("\tcontent=\"Free HTML5 Website Template by freehtml5.co\" />\r\n");
      out.write("<meta name=\"keywords\"\r\n");
      out.write("\tcontent=\"free website templates, free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive\" />\r\n");
      out.write("<meta name=\"author\" content=\"freehtml5.co\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/animate.css\">\r\n");
      out.write("<!-- Icomoon Icon Fonts-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/icomoon.css\">\r\n");
      out.write("<!-- Bootstrap  -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Magnific Popup -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Owl Carousel  -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.theme.default.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Flexslider  -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/flexslider.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Pricing -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/pricing.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Theme style  -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Modernizr JS -->\r\n");
      out.write("<script src=\"js/modernizr-2.6.2.min.js\"></script>\r\n");
      out.write("<!-- FOR IE9 below -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("\t<script src=\"js/respond.min.js\"></script>\r\n");
      out.write("\t<![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"fh5co-loader\"></div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"page\">\r\n");
      out.write("\t\t<nav class=\"fh5co-nav\" role=\"navigation\">\r\n");
      out.write("\t\t<div class=\"top\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"top-menu\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"fh5co-logo\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"index.html\"><i class=\"icon-study\"></i>TUTO<span>.</span></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-10 text-right menu-1\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <li><a href=\"courses.html\">Courses</a></li> -->\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"has-dropdown\"><a href=\"courses.html\">Courses</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"login.html\">Java</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"login.html\">C++</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"login.html\">Python</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"active\"><a href=\"Videos.html\">Videos</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"about.html\">About</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"contact.html\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t");
String n=null;
n=(String)session.getAttribute("Login_name");
      out.write('\r');
      out.write('\n');
      out.write(' ');
if (n != null){
	 System.out.println("inside if");
	 
      out.write("\r\n");
      out.write("\t \r\n");
      out.write("\t <li class=\"btn-cta\"><a href=\"LogoutServlet\"><span>logout</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<font face=\"Times New Roman\" size=\"4\">\r\n");
      out.write(" \t\t\t\t\t\t\t\t ");
String name1 = (String) session.getAttribute("Login_name");
      out.write("\r\n");
      out.write(" \t\t\t\t\t\t\t\t <br> welcome ");
      out.print(name1);
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write(" \t\t\t\t\t\t\t\t");
   }
  								 else {
  								 	 System.out.println("inside else");
  								 
      out.write("\r\n");
      out.write("  \t\t\t\t\t\t\t\t \r\n");
      out.write("      \t\t\t\t\t\t\t\t<li class=\"btn-cta\"><a href=\"login.html\"><span>Login</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"btn-cta\"><a href=\"register.html\"><span>Create\r\n");
      out.write("\t\t\t\t\t\t\t\t\ta Course</span></a></li>\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t");
 } 
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\t\t<center>\r\n");
      out.write("\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t<font face=\"Times New Roman\" size=\"4\">\r\n");
      out.write("\t\t\t\t\t\t");
String name=request.getParameter("name"); 
      out.write("<br> SUBJECT ");
      out.print(name );
      out.write("</font>\r\n");
      out.write("\t\t\t\t</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t<font face=\"Times New Roman\" size=\"4\">\r\n");
      out.write("\t\t\t\t\t\t");
String Desc=request.getParameter("decs"); 
      out.write("<br> ABOUT ");
      out.print(Desc );
      out.write("</font>\r\n");
      out.write("\t\t\t\t</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");
String id1=request.getParameter("cfile");
				String s="Courses-PDF"+"/"+id1+"."+"pdf";
			//	URL url=s.;
				Path p= Paths.get("Courses-PDF"+"/"+id1+"."+"pdf");
				URL u=URL.class.getResource(s);
								  System.out.print("\n"+s);
								  System.out.print("\n"+p);
							//	  System.out.print("\n"+u);

								  
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<div id=\"pdf-wrapper\" class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t<iframe src=\"Courses-PDF/");
      out.print(id1);
      out.write(".pdf\" id=\"showskill\" scrolling=\"yes\" height=\"600px\" width =\"100%\" type=\"application/pdf\">\t\t\t \r\n");
      out.write(" </iframe>\r\n");
      out.write("\t\t\t\r\n");
      out.write(" \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t</center>\r\n");
      out.write("\r\n");
      out.write("\t\t<footer id=\"fh5co-footer\" role=\"contentinfo\" style=\"background-image: url(images/img_bg_4.jpg);\">\r\n");
      out.write("\t\t<div class=\"overlay\"></div>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row row-pb-md\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 fh5co-widget\">\r\n");
      out.write("\t\t\t\t\t<h3>About Education</h3>\r\n");
      out.write("\t\t\t\t\t<p>âEducation is the most powerful weapon which you can use to change the world.â<br>Nelson Mandela</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-2 col-sm-4 col-xs-6 col-md-push-1 fh5co-widget\">\r\n");
      out.write("\t\t\t\t\t<h3>Learning</h3>\r\n");
      out.write("\t\t\t\t\t<ul class=\"fh5co-footer-links\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"courses.html\">Course</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"contact.html\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"about.html\">Terms</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-md-2 col-sm-4 col-xs-6 col-md-push-1 fh5co-widget\">\r\n");
      out.write("\t\t\t\t\t<h3>Learn &amp; Grow</h3>\r\n");
      out.write("\t\t\t\t\t<ul class=\"fh5co-footer-links\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"about.html\">Privacy</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"gototop js-top\">\r\n");
      out.write("\t\t<a href=\"#\" class=\"js-gotop\"><i class=\"icon-arrow-up\"></i></a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- jQuery -->\r\n");
      out.write("\t<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("\t<!-- jQuery Easing -->\r\n");
      out.write("\t<script src=\"js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("\t<!-- Bootstrap -->\r\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<!-- Waypoints -->\r\n");
      out.write("\t<script src=\"js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("\t<!-- Stellar Parallax -->\r\n");
      out.write("\t<script src=\"js/jquery.stellar.min.js\"></script>\r\n");
      out.write("\t<!-- Carousel -->\r\n");
      out.write("\t<script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("\t<!-- Flexslider -->\r\n");
      out.write("\t<script src=\"js/jquery.flexslider-min.js\"></script>\r\n");
      out.write("\t<!-- countTo -->\r\n");
      out.write("\t<script src=\"js/jquery.countTo.js\"></script>\r\n");
      out.write("\t<!-- Magnific Popup -->\r\n");
      out.write("\t<script src=\"js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/magnific-popup-options.js\"></script>\r\n");
      out.write("\t<!-- Count Down -->\r\n");
      out.write("\t<script src=\"js/simplyCountdown.js\"></script>\r\n");
      out.write("\t<!-- Main -->\r\n");
      out.write("\t<script src=\"js/main.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("    var d = new Date(new Date().getTime() + 1000 * 120 * 120 * 2000);\r\n");
      out.write("\r\n");
      out.write("    // default example\r\n");
      out.write("    simplyCountdown('.simply-countdown-one', {\r\n");
      out.write("        year: d.getFullYear(),\r\n");
      out.write("        month: d.getMonth() + 1,\r\n");
      out.write("        day: d.getDate()\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    //jQuery example\r\n");
      out.write("    $('#simply-countdown-losange').simplyCountdown({\r\n");
      out.write("        year: d.getFullYear(),\r\n");
      out.write("        month: d.getMonth() + 1,\r\n");
      out.write("        day: d.getDate(),\r\n");
      out.write("        enableUtc: false\r\n");
      out.write("    });\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
