/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.24
 * Generated at: 2019-10-03 11:14:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class courses_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t<title>Education &mdash; Free Website Template, Free HTML5 Template by freehtml5.co</title>\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t<meta name=\"description\" content=\"Free HTML5 Website Template by freehtml5.co\" />\r\n");
      out.write("\t<meta name=\"keywords\" content=\"free website templates, free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive\" />\r\n");
      out.write("\t<meta name=\"author\" content=\"freehtml5.co\" />\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/animate.css\">\r\n");
      out.write("\t<!-- Icomoon Icon Fonts-->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/icomoon.css\">\r\n");
      out.write("\t<!-- Bootstrap  -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Magnific Popup -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Owl Carousel  -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/owl.theme.default.min.css\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Flexslider  -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/flexslider.css\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Pricing -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/pricing.css\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Theme style  -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Modernizr JS -->\r\n");
      out.write("\t<script src=\"js/modernizr-2.6.2.min.js\"></script>\r\n");
      out.write("\t<!-- FOR IE9 below -->\r\n");
      out.write("\t<!--[if lt IE 9]>\r\n");
      out.write("\t<script src=\"js/respond.min.js\"></script>\r\n");
      out.write("\t<![endif]-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"fh5co-loader\"></div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"page\">\r\n");
      out.write("\t<nav class=\"fh5co-nav\" role=\"navigation\">\r\n");
      out.write("\t\t<div class=\"top\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<!-- <div class=\"col-xs-12 text-right\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"site\">www.yourdomainname.com</p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"num\">Call: +01 123 456 7890</p>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"fh5co-social\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"icon-facebook2\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"icon-twitter2\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"icon-dribbble2\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"icon-github\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"top-menu\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"fh5co-logo\"><a href=\"index.html\"><i class=\"icon-study\"></i>TUTO.<span></span></a></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-10 text-right menu-1\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <li class=\"active\"><a href=\"courses.html\">Courses</a></li> -->\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"has-dropdown\"><a href=\"courses.jsp\">Courses</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"login.html\">Java</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"login.html\">C++</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"login.html\">Python</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"Videos.jsp\">Videos</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"about.jsp\">About</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <li><a href=\"pricing.html\">Pricing</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"has-dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"blog.html\">Blog</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Web Design</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">eCommerce</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Branding</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">API</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li> -->\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"contactus.jsp\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t");
String n=null;
n=(String)session.getAttribute("Login_name");
      out.write('\r');
      out.write('\n');
      out.write(' ');
if (n != null){
	 System.out.println("inside if");
	 
      out.write("\r\n");
      out.write("\t \r\n");
      out.write("\t <li class=\"btn-cta\"><a href=\"LogoutServlet\"><span>logout</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<font face=\"Times New Roman\" size=\"4\">\r\n");
      out.write(" \t\t\t\t\t\t\t\t ");
String name1 = (String) session.getAttribute("Login_name");
      out.write("\r\n");
      out.write(" \t\t\t\t\t\t\t\t <br> welcome ");
      out.print(name1);
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write(" \t\t\t\t\t\t\t\t");
   }
  								 else {
  								 	 System.out.println("inside else");
  								 
      out.write("\r\n");
      out.write("  \t\t\t\t\t\t\t\t \r\n");
      out.write("      \t\t\t\t\t\t\t\t<li class=\"btn-cta\"><a href=\"login.html\"><span>Login</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"btn-cta\"><a href=\"register.html\"><span>Create\r\n");
      out.write("\t\t\t\t\t\t\t\t\ta Course</span></a></li>\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t");
 } 
      out.write("  \r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t<aside id=\"fh5co-hero\">\r\n");
      out.write("\t\t<div class=\"flexslider\">\r\n");
      out.write("\t\t\t<ul class=\"slides\">\r\n");
      out.write("\t\t   \t<li style=\"background-image: url(pics/22.jpg);\">\r\n");
      out.write("\t\t   \t\t<div class=\"overlay-gradient\"></div>\r\n");
      out.write("\t\t   \t\t<div class=\"container\">\r\n");
      out.write("\t\t   \t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t   \t\t\t<div class=\"col-md-8 col-md-offset-2 text-center slider-text\">\r\n");
      out.write("\t\t\t   \t\t\t\t<div class=\"slider-text-inner\">\r\n");
      out.write("\t\t\t   \t\t\t\t\t<h1 class=\"heading-section\">Our Course</h1>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h2> Tuto  <a href=\"http://w3school.com/\" target=\"_blank\">Start Learning Now !!! </a></h2>\r\n");
      out.write("\t\t\t   \t\t\t\t</div>\r\n");
      out.write("\t\t\t   \t\t\t</div>\r\n");
      out.write("\t\t\t   \t\t</div>\r\n");
      out.write("\t\t   \t\t</div>\r\n");
      out.write("\t\t   \t</li>\r\n");
      out.write("\t\t  \t</ul>\r\n");
      out.write("\t  \t</div>\r\n");
      out.write("\t</aside>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"fh5co-course\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row animate-box\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 col-md-offset-3 text-center fh5co-heading\">\r\n");
      out.write("\t\t\t\t\t<h2>Our Course</h2>\r\n");
      out.write("\t\t\t\t\t<!-- <p>Dignissimos asperiores vitae velit veniam totam fuga molestias accusamus alias autem provident. Odit ab aliquam dolor eius.</p> -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 animate-box\">\r\n");
      out.write("\t\t\t\t\t<div class=\"course\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"course-img\" style=\"background-image: url(pics/9.jpg);\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3><a href=\"#\">Java</a></h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Java is a general purpose, high-level programming language .\r\n");
      out.write("\t\t\t\t\t\t\t\tThe Java programming language was developed by a small team of engineers, known as the Green Team, who initiated the language in 1991.</p>\r\n");
      out.write("\t\t\t\t\t\t\t<span><a href=\"login.html\" class=\"btn btn-primary btn-sm btn-course\">Take A Trial</a></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 animate-box\">\r\n");
      out.write("\t\t\t\t\t<div class=\"course\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"login.html\" class=\"course-img\" style=\"background-image: url(pics/10.jpg);\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3><a href=\"#\">C++</a></h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p>C++ is a statically typed,compiled,case-sensitive,object-oriented.\r\n");
      out.write("\t\t\t\t\t\t\t\t C++ is regarded as a middle-level language, as it comprises a combination of both high-level and low-level language features.</p>\r\n");
      out.write("\t\t\t\t\t\t\t<span><a href=\"login.html\" class=\"btn btn-primary btn-sm btn-course\">Take A Trial</a></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 animate-box\">\r\n");
      out.write("\t\t\t\t\t<div class=\"course\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"course-img\" style=\"background-image: url(pics/8.jpg);\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3><a href=\"#\">Python</a></h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Python is an interpreted, object-oriented, high-level programming language with dynamic semantics.\r\n");
      out.write("\t\t\t\t\t\t\t\tPython's simple, easy to learn syntax emphasizes readability and therefore reduces the cost of program maintenance.</p>\r\n");
      out.write("\t\t\t\t\t\t\t<span><a href=\"login.html\" class=\"btn btn-primary btn-sm btn-course\">Take A Trial</a></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 animate-box\">\r\n");
      out.write("\t\t\t\t\t<div class=\"course\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"course-img\" style=\"background-image: url(pics/22.jpg);\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3><a href=\"login.html\">Web_Technology</a></h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Web technology refers by which computers communicate with each other using markup languages and multimedia packages.\r\n");
      out.write("\t\t\t\t\t\t\tProgramming languages and technologies that help create applications for the web.</p>\r\n");
      out.write("\t\t\t\t\t\t\t<span><a href=\"\" class=\"btn btn-primary btn-sm btn-course\">Take A Trial</a></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<footer id=\"fh5co-footer\" role=\"contentinfo\" style=\"background-image: url(images/img_bg_4.jpg);\">\r\n");
      out.write("\t\t<div class=\"overlay\"></div>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row row-pb-md\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 fh5co-widget\">\r\n");
      out.write("\t\t\t\t\t<h3>About Education</h3>\r\n");
      out.write("<p>âEducation is the most powerful weapon which you can use to change the world.â<br>Nelson Mandela</p>\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-2 col-sm-4 col-xs-6 col-md-push-1 fh5co-widget\">\r\n");
      out.write("\t\t\t\t\t<h3>Learning</h3>\r\n");
      out.write("\t\t\t\t\t<ul class=\"fh5co-footer-links\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Course</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"contact.html\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"about.html\">Terms</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-md-2 col-sm-4 col-xs-6 col-md-push-1 fh5co-widget\">\r\n");
      out.write("\t\t\t\t\t<h3>Learn &amp; Grow</h3>\r\n");
      out.write("\t\t\t\t\t<ul class=\"fh5co-footer-links\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"contact.html\">Privacy</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"gototop js-top\">\r\n");
      out.write("\t\t<a href=\"#\" class=\"js-gotop\"><i class=\"icon-arrow-up\"></i></a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- jQuery -->\r\n");
      out.write("\t<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("\t<!-- jQuery Easing -->\r\n");
      out.write("\t<script src=\"js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("\t<!-- Bootstrap -->\r\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<!-- Waypoints -->\r\n");
      out.write("\t<script src=\"js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("\t<!-- Stellar Parallax -->\r\n");
      out.write("\t<script src=\"js/jquery.stellar.min.js\"></script>\r\n");
      out.write("\t<!-- Carousel -->\r\n");
      out.write("\t<script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("\t<!-- Flexslider -->\r\n");
      out.write("\t<script src=\"js/jquery.flexslider-min.js\"></script>\r\n");
      out.write("\t<!-- countTo -->\r\n");
      out.write("\t<script src=\"js/jquery.countTo.js\"></script>\r\n");
      out.write("\t<!-- Magnific Popup -->\r\n");
      out.write("\t<script src=\"js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/magnific-popup-options.js\"></script>\r\n");
      out.write("\t<!-- Count Down -->\r\n");
      out.write("\t<script src=\"js/simplyCountdown.js\"></script>\r\n");
      out.write("\t<!-- Main -->\r\n");
      out.write("\t<script src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
