/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.24
 * Generated at: 2019-10-03 06:23:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ResetPassword_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/register.html", Long.valueOf(1569393756801L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\r\n");
      out.write("    \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("    <title>Reset Password</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/style.css\" >\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/js/jquery.validate.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<!-- <script type=\"text/javascript\">\r\n");
      out.write("function CheckPassword(inputtxt) \r\n");
      out.write("{ \r\n");
      out.write("var passw = /^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{6,20}$/;\r\n");
      out.write("if(inputtxt.value.match(passw)) \r\n");
      out.write("{ \r\n");
      out.write("alert('Correct, try another...')\r\n");
      out.write("return true;\r\n");
      out.write("}\r\n");
      out.write("else\r\n");
      out.write("{ \r\n");
      out.write("alert('Wrong...!')\r\n");
      out.write("return false;\r\n");
      out.write("}\r\n");
      out.write("}</script> -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("\tfont-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("\tmargin-top: 35px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add padding to containers */\r\n");
      out.write(".container {\r\n");
      out.write("\tpadding: 30px;\r\n");
      out.write("\talign: center;\r\n");
      out.write("\twidth: 30%;\r\n");
      out.write("\tbackground-color: #ABEBC6;\r\n");
      out.write("\toutline-color: #209982;\r\n");
      out.write("\toutline-style: solid;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Full-width input fields */\r\n");
      out.write("input[type=text], input[type=password] {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\tmargin: 5px 0 22px 0;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tbackground: #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=text]:focus, input[type=password]:focus {\r\n");
      out.write("\tbackground-color: #ddd;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("}\r\n");
      out.write("input[type=email], input[type=email] {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\tmargin: 5px 0 22px 0;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tbackground: #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=email]:focus, input[type=email]:focus {\r\n");
      out.write("\tbackground-color: #ddd;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Overwrite default styles of hr */\r\n");
      out.write("hr {\r\n");
      out.write("\tborder: 1px solid #f1f1f1;\r\n");
      out.write("\tmargin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Set a style for the submit button */\r\n");
      out.write(".registerbtn {\r\n");
      out.write("\tbackground-color: #4CAF50;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tpadding: 10px 10px;\r\n");
      out.write("\tmargin: 8px 0;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\topacity: 0.9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".registerbtn:hover {\r\n");
      out.write("\topacity: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add a blue text color to links */\r\n");
      out.write("a {\r\n");
      out.write("\tcolor: dodgerblue;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Set a grey background color and center the text of the \"sign in\" section */\r\n");
      out.write(".signin {\r\n");
      out.write("\tbackground-color: #f1f1f1;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bg {\r\n");
      out.write("\t/* The image used */\r\n");
      out.write("\tbackground-image: url(\"image.jpg\");\r\n");
      out.write("\t/* Full height */\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\t/* Center and scale the image nicely */\r\n");
      out.write("\tbackground-position: center;\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("\tbackground-size: cover;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg\">\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<form action=\"SignupServlet\" method=\"post\" >\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<h1 align=\"center\">Register</h1>\r\n");
      out.write("\t\t\t\t<p align=\"center\">Please fill in this form to create an account.</p>\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t<label for=\"USERNAME\"><b>Name</b></label> \r\n");
      out.write("\t\t\t\t<input type=\"text\" size=\"number\" placeholder=\"Enter Name\" name=\"name\" on required> \r\n");
      out.write("\t\t\t\t<label\tfor=\"email\"><b>Email</b></label><br> \r\n");
      out.write("\t\t\t\t\t<input type=\"email\"  placeholder=\"Enter Email\" name=\"email\"\r\n");
      out.write("\t\t\t\t\trequired><br>\r\n");
      out.write("\t\t\t\t\t<label for=\"psw\"><b>Password</b></label>\r\n");
      out.write("   \r\n");
      out.write("\t\t\t\t <input type=\"password\" size=\"number\" placeholder=\"Enter Password\" name=\"psw\" \r\n");
      out.write("\t\t\t\t  required>  \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<button type=\"submit\" class=\"registerbtn\" \">Register</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"container signin\">\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\tAlready have an account? <a href=\"login.html\">Sign in</a>.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</center>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("    <div align=\"center\">\r\n");
      out.write("        <h2>Reset Your Password</h2>\r\n");
      out.write("        <p>\r\n");
      out.write("        Please enter your login email, we'll send a new random password to your inbox:\r\n");
      out.write("        </p>\r\n");
      out.write("         \r\n");
      out.write("        <form id=\"resetForm\" action=\"reset_password\" method=\"post\">\r\n");
      out.write("            <table>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>Email:</td>\r\n");
      out.write("                    <td><input type=\"text\" name=\"email\" id=\"email\" size=\"20\"></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td colspan=\"2\" align=\"center\">\r\n");
      out.write("                        <button type=\"submit\">Send me new password</button>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>    \r\n");
      out.write("            </table>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("     \r\n");
      out.write("    ");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<!-- <script type=\"text/javascript\">\r\n");
      out.write("function CheckPassword(inputtxt) \r\n");
      out.write("{ \r\n");
      out.write("var passw = /^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{6,20}$/;\r\n");
      out.write("if(inputtxt.value.match(passw)) \r\n");
      out.write("{ \r\n");
      out.write("alert('Correct, try another...')\r\n");
      out.write("return true;\r\n");
      out.write("}\r\n");
      out.write("else\r\n");
      out.write("{ \r\n");
      out.write("alert('Wrong...!')\r\n");
      out.write("return false;\r\n");
      out.write("}\r\n");
      out.write("}</script> -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("\tfont-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("\tmargin-top: 35px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add padding to containers */\r\n");
      out.write(".container {\r\n");
      out.write("\tpadding: 30px;\r\n");
      out.write("\talign: center;\r\n");
      out.write("\twidth: 30%;\r\n");
      out.write("\tbackground-color: #ABEBC6;\r\n");
      out.write("\toutline-color: #209982;\r\n");
      out.write("\toutline-style: solid;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Full-width input fields */\r\n");
      out.write("input[type=text], input[type=password] {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\tmargin: 5px 0 22px 0;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tbackground: #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=text]:focus, input[type=password]:focus {\r\n");
      out.write("\tbackground-color: #ddd;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("}\r\n");
      out.write("input[type=email], input[type=email] {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\tmargin: 5px 0 22px 0;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tbackground: #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=email]:focus, input[type=email]:focus {\r\n");
      out.write("\tbackground-color: #ddd;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Overwrite default styles of hr */\r\n");
      out.write("hr {\r\n");
      out.write("\tborder: 1px solid #f1f1f1;\r\n");
      out.write("\tmargin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Set a style for the submit button */\r\n");
      out.write(".registerbtn {\r\n");
      out.write("\tbackground-color: #4CAF50;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tpadding: 10px 10px;\r\n");
      out.write("\tmargin: 8px 0;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\topacity: 0.9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".registerbtn:hover {\r\n");
      out.write("\topacity: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add a blue text color to links */\r\n");
      out.write("a {\r\n");
      out.write("\tcolor: dodgerblue;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Set a grey background color and center the text of the \"sign in\" section */\r\n");
      out.write(".signin {\r\n");
      out.write("\tbackground-color: #f1f1f1;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bg {\r\n");
      out.write("\t/* The image used */\r\n");
      out.write("\tbackground-image: url(\"image.jpg\");\r\n");
      out.write("\t/* Full height */\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\t/* Center and scale the image nicely */\r\n");
      out.write("\tbackground-position: center;\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("\tbackground-size: cover;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg\">\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<form action=\"SignupServlet\" method=\"post\" >\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<h1 align=\"center\">Register</h1>\r\n");
      out.write("\t\t\t\t<p align=\"center\">Please fill in this form to create an account.</p>\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t<label for=\"USERNAME\"><b>Name</b></label> \r\n");
      out.write("\t\t\t\t<input type=\"text\" size=\"number\" placeholder=\"Enter Name\" name=\"name\" on required> \r\n");
      out.write("\t\t\t\t<label\tfor=\"email\"><b>Email</b></label><br> \r\n");
      out.write("\t\t\t\t\t<input type=\"email\"  placeholder=\"Enter Email\" name=\"email\"\r\n");
      out.write("\t\t\t\t\trequired><br>\r\n");
      out.write("\t\t\t\t\t<label for=\"psw\"><b>Password</b></label>\r\n");
      out.write("   \r\n");
      out.write("\t\t\t\t <input type=\"password\" size=\"number\" placeholder=\"Enter Password\" name=\"psw\" \r\n");
      out.write("\t\t\t\t  required>  \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<button type=\"submit\" class=\"registerbtn\" \">Register</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"container signin\">\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\tAlready have an account? <a href=\"login.html\">Sign in</a>.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</center>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" \r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("        $(\"#resetForm\").validate({\r\n");
      out.write("            rules: {\r\n");
      out.write("                email: {\r\n");
      out.write("                    required: true,\r\n");
      out.write("                    email: true\r\n");
      out.write("                }      \r\n");
      out.write("            },\r\n");
      out.write("             \r\n");
      out.write("            messages: {\r\n");
      out.write("                email: {\r\n");
      out.write("                    required: \"Please enter email\",\r\n");
      out.write("                    email: \"Please enter a valid email address\"\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write(" \r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
